version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "3333:3333" 
  print:
    build:
      context: .
      dockerfile: Dockerfile-print
    ports:
      - "4200:80"     