FROM node:14-slim As development

WORKDIR /usr/src

COPY . .

RUN npm install minimist \
    && npm install --only=development 

RUN npm run build

FROM nginx:stable as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=development /usr/src/dist/apps/print /usr/share/nginx/html

ENTRYPOINT ["nginx", "-g", "daemon off;"]
