FROM node:14-slim As development

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src

COPY . .

RUN npm install minimist \
    && npm install --only=development 

RUN npm run build:api

FROM alpine:edge As production

WORKDIR /usr/src

COPY package*.json tsconfig.*.json ./
COPY --from=development /usr/src/dist/apps ./dist

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV} \
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# Installs latest Chromium (77) package.
RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      freetype-dev \
      harfbuzz \
      ca-certificates \
      ttf-freefont \
      nodejs \
      npm

RUN npm install --only=production 


CMD ["node", "dist/api/main"]
